[package]
name = "commandant-core"
version = "0.0.1"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
rusqlite = {version = "0.32.1", features = ["bundled"] }
uuid = {version = "1.22.0", features = ["v4", "serde"] }
lmrc-docker = "0.3.16"
tokio = { version = "1.50.0", features = ["full"] }

[lints]
workspace = true
